name: cea
channels:
- conda-forge
- defaults
dependencies:
- deap
- ephem
- flask
- flask-cors
- flask-restx
- flask-socketio
- werkzeug==2.0.*
- gevent
- gevent-websocket
- ipykernel
- ipython
- jupyter
- openpyxl
- plotly
- sphinx
- sympy
- utm
- fiona
- gdal
- geopandas
- matplotlib
- networkx
- numba
- numpy
- numpy-financial
- osmnx=0.15.1
- pandas
- pip
- psutil
- libpysal
- pythonocc-core
- pytz
- pvlib-python
- scipy
- setuptools
- shapely
- pyyaml
- timezonefinder
- python-cufflinks
- cvxopt # For wntr
- pip:
  - xlrd
  - xlwt
  - staticmap
  - wntr==0.2.*
  - git+https:///github.com/reyery/py4design.git@cea # modified p4design to remove deprecated functions

