name: cea
channels:
- conda-forge
- defaults
dependencies:
- deap
- ephem
- flask
- flask-cors
- flask-restx
- flask-socketio
- notebook
- openpyxl
- plotly
- sphinx
- utm
- fiona
- geopandas<0.14
- matplotlib-base
- networkx<3
- numba==0.58.*
- numpy==1.26.*
- numpy-financial
- osmnx
- pip
- psutil
- libpysal
- pythonocc-core
- pytz
- pvlib-python
- scipy
- shapely
- pyyaml
- timezonefinder
- python-cufflinks
- cvxopt # For wntr
- python=3.8 # Held back by wntr version
- pip:
  - xlrd
  - xlwt
  - staticmap
  - wntr==0.2.3
  - git+https://github.com/reyery/py4design.git@cea # modified p4design to remove deprecated functions
  - simple-websocket
  - pyarrow
