name: cea
channels:
- conda-forge
dependencies:
- deap
- ephem
- fiona
- geopandas=0.13 # Due to python3.8 support
- networkx=2.8
- numba=0.57
- numpy=1.24 # Due to python3.8 support
- numpy-financial
- osmnx=1.8
- pip
- psutil
- libpysal
- pythonocc-core==7.7.0 # Avoid deprecation warnings
- pvlib-python
- scipy=1.10 # Due to python3.8 support
- shapely=2
- pyyaml
- timezonefinder
- cvxopt # For wntr
- python=3.8 # Held back by wntr version
- pip:
  - cufflinks
  - flask
  - flask-cors
  - flask-restx
  - flask-socketio
  - matplotlib
  - notebook
  - openpyxl
  - plotly
  - pytz # Not required from 3.9
  - sphinx
  - utm
  - xlrd
  - xlwt
  - staticmap
  - wntr==0.2.3
  - git+https://github.com/reyery/py4design.git@cea # modified p4design to remove deprecated functions
  - simple-websocket
  - pyarrow
