name: cea
channels:
- conda-forge
dependencies:
- cvxopt # For wntr
- deap
- ephem
- fiona
- aiocache
- fastapi
- pydantic-settings
- uvicorn-standard
- jinja2
- python-socketio
- geopandas=0.13 # Due to python3.8 support
- libpysal
- networkx=2.8
- numba=0.57
- numpy=1.24 # Due to python3.8 support
- numpy-financial
- osmnx=1.8
- pip
- psutil
- pvlib-python
- pythermalcomfort
- python=3.8 # Held back by wntr version
- python-louvain
- pythonocc-core==7.7.0 # Avoid deprecation warnings
- pytz # Not required from 3.9
- pyyaml
- salib
- scikit-learn=1.3.2
- scipy=1.10 # Due to python3.8 support
- shapely=2
- timezonefinder
- matplotlib
- notebook
- openpyxl
- plotly
- utm
- xlrd
- xlwt
- pyarrow
- git
- yarn=4 # Use latest version of yarn
- python-multipart # Required by fastapi for file uploads
- pip:
  - wntr==0.2.3
  - git+https://github.com/reyery/py4design.git@ignore-display # modified p4design to remove deprecated functions
