name: cea
channels:
- conda-forge
dependencies:
- cvxopt # For wntr
- fiona
- geopandas
- libpysal
- numba
- numpy
- osmnx
- networkx
- pip
- psutil
- pvlib
- python=3.10
- pythonocc-core==7.7.0 # Avoid deprecation warnings
- pyyaml
- scikit-learn
- scipy
- shapely=2
- matplotlib
- notebook
- pyarrow
