name: cea
channels:
- conda-forge
- defaults
dependencies:
- deap
- ephem
- flask
- flask-cors
- flask-restx
- flask-socketio
- werkzeug==2.0.*
- ipykernel
- ipython
- jupyter
- openpyxl
- plotly
- sphinx
- utm
- fiona
- gdal
- geopandas
- matplotlib
- networkx<3
- numba
- numpy<1.24
- numpy-financial
- osmnx==1.2.2
- pandas<2
- pip
- psutil
- libpysal
- pythonocc-core
- pytz
- pvlib-python
- scipy
- shapely
- pyyaml
- timezonefinder
- python-cufflinks
- cvxopt # For wntr
- pyarrow
- pip:
  - xlrd
  - xlwt
  - staticmap
  - wntr==0.2.*
  - git+https:///github.com/reyery/py4design.git@cea # modified p4design to remove deprecated functions
  - simple-websocket

