name: cea
channels:
- conda-forge
dependencies:
# Python version and pip
- python=3.12
- pip
#Dependencies for CEA
- cvxopt # For wntr
- fiona
- gdal
- geopandas
- libpysal
- numba
- numpy<2 # held back by wntr
- osmnx
- networkx>=3.4 # 3.4 contains a fix for steiner tree algorithm
- psutil
- pvlib
- pythonocc-core
- pyyaml
- scikit-learn
- scipy
- shapely
- matplotlib
- notebook
- pyarrow
