[project]
name = "cityenergyanalyst"
description = "City Energy Analyst"
readme = "README.rst"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Architecture and Building Systems", email = "cea@arch.ethz.ch" }
]
maintainers = [
    { name = "Reynold Mok", email = "reynold.mok@arch.ethz.ch" }
]
dynamic = ["version"]

dependencies = [
    # Backend dependencies
    "aiofiles",
    "aiocache[redis]",
    "fastapi",
    "pydantic-settings",
    "uvicorn",
    "jinja2",
    "python-socketio",
    "python-multipart",
    "sqlalchemy[asyncio]",
    "sqlmodel",
    "asyncpg",
    "aiosqlite",
    "pyjwt[crypto]",

    # Other python dependencies
    "deap",
    "ephem",
    "numpy-financial",
    "python-louvain",
    "pytz",
    "salib",
    "timezonefinder",
    "openpyxl",
    "plotly",
    "utm",
    "xlrd",
    "xlwt",
    "wntr"
]

[project.optional-dependencies]
dev = ["pytest", "ruff"]
docs = ["setuptools"]

[project.urls]
"Homepage" = "https://cityenergyanalyst.com"
"Bug Reports" = "https://github.com/architecture-building-systems/CityEnergyAnalyst/issues"
"Source" = "https://github.com/architecture-building-systems/CityEnergyAnalyst"

[project.scripts]
cea = "cea.interfaces.cli.cli:main"
cea-config = "cea.interfaces.cli.cea_config:main"
cea-doc = "cea.interfaces.cli.cea_doc:main"
cea-dev = "cea.interfaces.cli.cea_dev:main"
cea-worker = "cea.worker:main"
cea-plot = "cea.plots.plot_cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["cea*"]
namespaces = false

[tool.setuptools.dynamic]
version = { attr = "cea.__version__" }

[tool.ruff]
exclude = ["*.ipynb"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tool.pixi.tasks]
dashboard = "cea dashboard"
test = "cea test --type integration"

[tool.pixi.dependencies]
cvxopt = "*"
fiona = "*"
gdal = "*"
geopandas = "*"
libpysal = "*"
numba = "*"
numpy = "*"
osmnx = "*"
networkx = "*"
psutil = "*"
pvlib = "*"
pythonocc-core = "*"
pyyaml = "*"
scikit-learn = "*"
scipy = "*"
shapely = "*"
matplotlib = "*"
notebook = "*"
pyarrow = "*"
pixi-pycharm = ">=0.0.8,<0.0.9"

[tool.pixi.pypi-dependencies]
# install cea as editable package for development
cityenergyanalyst = { path = ".", editable = true }
