[project]
name = "cityenergyanalyst"
description = "City Energy Analyst"
readme = "README.rst"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Architecture and Building Systems", email = "cea@arch.ethz.ch" }
]
maintainers = [
    { name = "Reynold Mok", email = "reynold.mok@arch.ethz.ch" }
]
dynamic = ["version"]

dependencies = [
    # Backend dependencies
    "aiofiles",
    "aiocache[redis]",
    "fastapi",
    "pydantic-settings",
    "uvicorn",
    "jinja2",
    "python-socketio",
    "python-multipart", # Required by fastapi for file uploads
    "sqlalchemy[asyncio]",
    "sqlmodel", # Required by fastapi for database models
    "asyncpg", # Required by sqlmodel for postgres
    "aiosqlite", # Required for async sqlite adapter
    "pyjwt[crypto]", # Required by fastapi for JWT authentication

    # Other python dependencies
    "deap",
    "ephem",
    "numpy-financial",
    "python-louvain",
    "pytz", # Not required from 3.9
    "salib",
    "timezonefinder",
    "openpyxl",
    "plotly",
    "utm",
    "xlrd",
    "xlwt",
    "wntr>=1.3.2,<2", # Needs to be installed via pip since conda-forge does not provide osx-arm64 builds

    # modified p4design to remove deprecated functions
    "py4design @ git+https://github.com/reyery/py4design.git@08326122ee496afbf762527365d88415f4b570f5",
]

[project.optional-dependencies]
dev = ["pytest", "ruff"]
docs = ["setuptools"]

[project.urls]
"Homepage" = "https://cityenergyanalyst.com"
"Bug Reports" = "https://github.com/architecture-building-systems/CityEnergyAnalyst/issues"
"Source" = "https://github.com/architecture-building-systems/CityEnergyAnalyst"

[project.scripts]
cea = "cea.interfaces.cli.cli:main"
cea-config = "cea.interfaces.cli.cea_config:main"
cea-doc = "cea.interfaces.cli.cea_doc:main"
cea-dev = "cea.interfaces.cli.cea_dev:main"
cea-worker = "cea.worker:main"
cea-plot = "cea.plots.plot_cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["cea*"]
namespaces = false

[tool.setuptools.dynamic]
version = { attr = "cea.__version__" }

[tool.ruff]
exclude = ["*.ipynb"]
lint.ignore = [
    "E741", # ambiguous variable name (l, O, I)
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tool.pixi.tasks]
cea = "cea"
server = "cea dashboard"
test = "cea test --type integration"

[tool.pixi.dependencies]
cvxopt = "*" # For wntr
fiona = "*"
gdal = "*"
geopandas = "*"
libpysal = "*"
numba = "*"
numpy = "<2" # held back by wntr
osmnx = "*"
networkx = ">=3.4" # 3.4 contains a fix for steiner tree algorithm
psutil = "*"
pvlib = "*"
pythonocc-core = "*"
pyyaml = "*"
scikit-learn = "*"
scipy = "*"
shapely = "*"
matplotlib = "*"
notebook = "*"
pyarrow = "*"
pixi-pycharm = ">=0.0.8,<0.0.9" # for pycharm support

[tool.pixi.pypi-dependencies]
# install cea as editable package for development
cityenergyanalyst = { path = ".", editable = true }
