name: Ruff
on:
  pull_request:
    paths: ['cea/**']
  push:
    branches: [master]
    paths: ['cea/**']

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: clonedSemicolon/setup-strace@v13
    - name: Run Ruff Linter
      uses: astral-sh/ruff-action@v2
      with:
        src: ./cea
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
