name: Push to Master

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: apt update && apt install -y libgl1

      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: cea

      - name: Cache conda env
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n cea -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install CEA
        shell: bash -l {0}
        run: pip install .

      - name: Run tests
        shell: bash -l {0}
        run: cea test --workflow slow

  badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make Code Badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./output/badge-lines-of-code.svg
          ignore: "node_modules/|README"

      - name: Print the output
        run: |
          echo "Scanned: ${{ steps.badge.outputs.counted_files }}";
          echo "Line Count: ${{ steps.badge.outputs.total_lines }}";

      - name: Deploy to image-data branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
