name: Push to Master

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get clean && sudo apt-get update
          sudo apt-get install -y libgl1

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true

      - name: Install CEA
        shell: bash -l {0}
        run: pip install .

      - name: Run tests
        shell: bash -l {0}
        run: cea test --workflow slow
