name: Pull Request Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]

jobs:
  check_environment_yml:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.environment_yml_diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup master branch locally without switching current branch
        run: git fetch origin master:master
      - name: Check environment.yml diff
        id: environment_yml_diff
        run: |
          git diff --quiet ..master -- environment.yml
          echo "diff=$?" >> "$GITHUB_OUTPUT"

  warn_user:
    runs-on: ubuntu-latest
    needs: check_environment_yml
    if: ${{ needs.check_environment_yml.outputs.diff  == 1 }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Changes detected in `environment.yml`.'
            })

  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: cea
          cache-environment: true

      - name: Install CEA
        shell: bash -l {0}
        run: pip install .

      - name: Run tests
        shell: bash -l {0}
        run: cea test --workflow quick
