name: Pull Request test

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          miniforge-variant: Mambaforge
          miniforge-version: latest
          environment-file: environment.yml
          activate-environment: cea
      - name: Install cea
        shell: bash -l {0}
        run: pip install .
      - name: Run tests
        shell: bash -l {0}
        run: cea test --workflow quick
