name: Pull Request Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]

jobs:
  conda-lock:
    name: Compare conda-lock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for changes in environment.yml
        if: git diff --quiet HEAD..master -- environment.yml
        run: exit 0

      - name: Install conda-lock with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: ci
          create-args: conda-lock
          init-shell: bash

      - name: Run conda-lock
        run: conda-lock --mamba -f environment.yml -p osx-64 -p linux-64 -p win-64 --lockfile ${{ runner.temp }}/conda-lock.yml
        shell: bash -el {0}

      - name: Compare conda-lock hash
        if: ${{ hashFiles('conda-lock.yml') != hashFiles(format('{0}/conda-lock.yml', runner.temp)) }}
        run: exit 1

  build:
    name: ${{ matrix.os }}
    needs: conda-lock
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: cea
          cache-environment: true

      - name: Install CEA
        shell: bash -l {0}
        run: pip install .

      - name: Run tests
        shell: bash -l {0}
        run: cea test --workflow quick
