name: Build CEA Windows setup

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Install conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true
          environment-name: cea

      - name: Install CEA to conda environment
        shell: bash -l {0}
        run: pip install .

      - name: Install conda-pack
        run: micromamba create -n conda-pack conda-pack

      - name: Pack conda environment
        shell: bash -l {0}
        run: |
          micromamba activate conda-pack
          conda-pack -p $MAMBA_ROOT_PREFIX/envs/cea -o $GITHUB_WORKSPACE/cea.tar.gz

      - name: Extract tar
        shell: bash
        run: |
          tar -xzf $GITHUB_WORKSPACE/cea.tar.gz -C $GITHUB_WORKSPACE/setup/Dependencies/Python --force-local

      - name: Create sdist of CEA
        shell: bash
        run: |
          python setup.py sdist
          mv $GITHUB_WORKSPACE/dist/cityenergyanalyst-*.tar.gz $GITHUB_WORKSPACE/setup/Dependencies/cityenergyanalyst.tar.gz

      - name: Clone GUI repo
        uses: actions/checkout@v3
        with:
          repository: architecture-building-systems/CityEnergyAnalyst-GUI
          path: GUI

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Package CEA GUI
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/GUI
          yarn package
          mv out/CityEnergyAnalyst-GUI-win32-x64 $GITHUB_WORKSPACE/setup/CityEnergyAnalyst-GUI-win32-x64

      - name: Upload setup
        uses: actions/upload-artifact@v3
        with:
          name: setup
          path: $GITHUB_WORKSPACE\setup\Output
