name: Build CEA Windows setup

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: "windows-latest"
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Install makensis
        run: winget install NSIS.NSIS

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true

      - name: Install CEA
        shell: bash -l {0}
        run: pip install .
